# Generated by Django 5.0.7 on 2026-02-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Swypora', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='core/application/images')),
                ('tagline', models.CharField(blank=True, help_text='Short tagline', max_length=200, null=True)),
                ('contact_email', models.EmailField(default='support@swypora.com', max_length=100)),
                ('contact_phone', models.CharField(default='will be updated soon', max_length=100)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(default='Address to be updated', max_length=255)),
                ('facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter', models.URLField(blank=True, max_length=255, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram', models.URLField(blank=True, max_length=255, null=True)),
                ('youtube', models.URLField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Application',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(help_text='Full Name', max_length=50)),
                ('subject', models.CharField(help_text='Message Subject', max_length=100)),
                ('message', models.TextField(help_text='Your Message', max_length=1000)),
                ('email', models.EmailField(help_text='Your Email Address', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_replied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Form Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('payments', 'Payments'), ('hardware', 'Hardware'), ('pricing', 'Pricing'), ('support', 'Support')], default='general', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('service_type', models.CharField(choices=[('payment_processing', 'Payment Processing'), ('pos_system', 'POS System'), ('hardware', 'Hardware'), ('software_integration', 'Software Integration'), ('consultation', 'Consultation'), ('other', 'Other')], max_length=50)),
                ('project_title', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('budget_range', models.CharField(choices=[('under_1k', 'Under $1,000'), ('1k_5k', '$1,000 - $5,000'), ('5k_10k', '$5,000 - $10,000'), ('10k_25k', '$10,000 - $25,000'), ('above_25k', 'Above $25,000'), ('not_sure', 'Not Sure')], max_length=20)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Quote Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_position', models.CharField(blank=True, max_length=100, null=True)),
                ('client_company', models.CharField(blank=True, max_length=100, null=True)),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('rating', models.IntegerField(default=5, help_text='Rating out of 5')),
                ('testimonial', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
